version: '3'

services:
  designer:
      build:
          context: .
          dockerfile: Dockerfile
      container_name: sql2mqtt-graph-designer
      network_mode: host
      restart: unless-stopped
      volumes:
        - ./sql2mqtt-graph-designer.ini:/app/sql2mqtt-graph-designer.ini